import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import Header from "@/components/Header/header";
import ChiffresCles from "@/components/ChiffresCles/chiffresCles";
import Presentation from "@/components/Presentation/presentation";
import ContactBanner from "@/components/ContactBanner/contactBanner";
import dynamic from "next/dynamic";

export default function Home() {
  const DynamicFooter = dynamic(
    () => import("@/components/Footer/footer.jsx"),
    {
      ssr: false,
    }
  );
  return (
    <>
      <Head>
        <title>Mc Montage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <Presentation />
        <ChiffresCles />
        <ContactBanner />
        <DynamicFooter />
      </main>
    </>
  );
}
