import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import Header from "@/components/Header/header";
import "primereact/resources/themes/lara-light-indigo/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mc Montage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <div className={styles.container__text}>
          <p>
            MC Montage est une société spécialisée dans le montage de
            rayonnages, pose de cloison, mezzanine, faux plafond et
            d&apos;agencement de bureau depuis plus de 14 ans.
          </p>
          <p>
            Les chantiers sont principalement dans la région du Grand EST mais
            également dans toute la France et même à l&apos;étranger.
          </p>
        </div>
      </main>
    </>
  );
}
